name = "IteratedIntegrals"
uuid = "2d8b4e74-eb68-11e8-0fb9-d5eb67b50637"
authors = ["Felix Kastner <kastner.felix@gmail.com>"]
version = "0.1.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
SpecialFunctions = "1, 2"
julia = "1.3"
