name: CI
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.3'
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' }}
    steps:
      - name: Git checkout repository
        uses: actions/checkout@v2
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Run tests
        uses: julia-actions/julia-runtest@v1